# Generated by Django 3.2 on 2021-05-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('rel_date', models.CharField(max_length=8)),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='movieBlog/')),
            ],
        ),
    ]
